## Dotbot defaults
- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true
## Dotbot initialization
- clean: ['~']
- shell:
  - git submodule update --init --recursive
## Common shell configurations
- shell:
  - mkdir -p ~/.rc.d
- link:
    ~/.rc: config/base/rc
