- link:
    ~/.profile: shell/sh/profile
    ~/.bash_profile: shell/bash/bash_profile
    ~/.bashrc: shell/bash/bashrc

- shell:
  - "[ -f ~/.antigen.sh ] || curl -L git.io/antigen > ~/.antigen.zsh"

- link:
    ~/.zshrc: shell/zsh/zshrc
