tap "homebrew/core"
tap "caskroom/cask"
brew "cloc"
brew "shellcheck"
brew "ssh-copy-id"
brew "thefuck"
brew "tldr"
cask "1password"
cask "1password-cli"
cask "docker"
cask "dropbox"
cask "font-fira-code"
cask "gitter"
cask "google-backup-and-sync"
cask "google-chrome"
cask "slack"
cask "vagrant"
cask "virtualbox"
mas "Bear", id: 1091189122
mas "Magnet", id: 441258766
mas "The Unarchiver", id: 425424353
