# config.yaml
- defaults:
    link:
      create: true
      relink: true

# bash/config.yaml
- link:
    ~/.bash-it: bash/bash-it
    ~/.bash_profile: bash/bash_profile
    ~/.bashrc: bash/bashrc

# brew/config.macos.yaml
- brewfile:
    file: brew/Brewfile

# conda/config.yaml
- link:
    ~/.bash-it/custom/conda.bash: conda/conda.bash

# git/config.yaml
- link:
    ~/.bash-it/custom/git.bash: git/git.bash
    ~/.gitconfig: git/gitconfig

# hyper/config.macos.yaml
- link:
    ~/.hyper.js: hyper/hyper.js

# macos/config.macos.yaml
- link:
    ~/.gitignore/macOS.gitignore: git/gitignore/Global/macOS.gitignore

# ssh/config.yaml
- link:
    ~/.ssh/config: ssh/config

# vscode/config.macos.yaml
- link:
    ~/.gitignore/VisualStudioCode.gitignore: git/gitignore/Global/VisualStudioCode.gitignore
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json

