#!/usr/bin/env bash

source install-common.sh


"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" $PLUGIN -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

for config in ${@}; do
    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" $PLUGIN -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
done
