#!/usr/bin/env bash

set -e

CONFIG="config.yaml"
DOTBOT_DIR="tools/dotbot"

DOTBOT_BIN="bin/dotbot"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PLUGINS="--plugin-dir tools/dotbot-brewfile"

# Update submodules
cd "${BASEDIR}"
#git submodule update --init --recursive "${DOTBOT_DIR}"

# Get profile name
PROFILE="${@}"

# Add general configuration
CONFIG_FILES="${CONFIG}"

# Add profile configuration
PROFILE_CONFIG="${PROFILE}.${CONFIG}"
if [ -f $PROFILE_CONFIG ]; then
  CONFIG_FILES+=" $PROFILE_CONFIG"
fi

# Add configurations for each component
for CONFIG_FILE in "${BASE_DIR}/*/${CONFIG}"; do
    CONFIG_FILES+=" ${CONFIG_FILE}"
done
for CONFIG_FILE in "${BASE_DIR}/*/${PROFILE_CONFIG}"; do
    CONFIG_FILES+=" ${CONFIG_FILE}"
done

# Install
TEMP_CONFIG="${BASE_DIR}/temp_config.yaml"
cat ${CONFIG_FILES} > ${TEMP_CONFIG}
"${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" $PLUGINS -c ${TEMP_CONFIG}
rm ${TEMP_CONFIG}
