#!/usr/bin/env bash

source install-common.sh


while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "${META_DIR}/${PROFILES_DIR}/$1"

shift

CONFIG_FILES="${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

for config in ${CONFIGS} ${@}; do
    CONFIG_FILES+=" ${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
done

TEMP_CONFIG="${BASE_DIR}/install.conf.yaml"
cat ${CONFIG_FILES} > ${TEMP_CONFIG}
"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" $PLUGIN -c ${TEMP_CONFIG}
rm ${TEMP_CONFIG}
