# Dotbot config
- defaults:
    link:
      create: true
      relink: true
    shell:
      stdout: true

# General
- clean: ['~']
- link:
    ~/.rc: config/rc
- shell:
  - git submodule update --init --recursive

# Brew
- shell:
  - which brew || script/install-brew.sh
- env:
    PATH: "{HOME}/.linuxbrew/bin:{PATH}"

# Conda
- shell:
  - which conda || script/install-conda.sh
- link:
    ~/.condarc: config/condarc

# Git
- link:
    ~/.gitconfig: config/gitconfig

# Mercurial
- link:
    ~/.hgrc: config/hgrc

# SSH
- link:
    ~/.ssh/config: config/ssh/config
