name: lab
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - black
  - bokeh
  - cython
  - dask
  - doit
  - ipyvolume
  - jinja2
  - jupyterlab
  - networkx
  - nodejs
  - numba
  - numpy
  - matplotlib
  - pandas
  - papermill
  - pillow
  - pip
  - pylint
  - pytest
  - python
  - scipy
  - seaborn
  - sphinx
  - sympy
  - unyt
  - yt
  - pip:
    - py-spy
