- link:
    ~/.gitignore/VisualStudioCode.gitignore: vcs/git/gitignore/Global/VisualStudioCode.gitignore
    ~/Library/Application Support/Code/User/settings.json: config/vscode/settings.json

- link:
    ~/.hyper.js: terminal/hyper/hyper.js
