# hyper
- link:
    ~/.hyper.js: config/hyper/hyper.js

# system
- link:
    ~/.gitignore/macOS.gitignore: config/gitignore/Global/macOS.gitignore

# vscode
- link:
    ~/.gitignore/VisualStudioCode.gitignore: config/gitignore/Global/VisualStudioCode.gitignore
    ~/Library/Application Support/Code/User/settings.json: config/vscode/settings.json

# zsh
- link:
    ~/.zshrc: config/zshrc
