if [ -f ~/.zshrc_before ]; then
    source ~/.zshrc_before
fi


# oh-my-zsh
# https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template

export ZSH=$HOME/.local/opt/oh-my-zsh
plugins=(
  git
)

# powerlevel9k theme
# https://github.com/bhilburn/powerlevel9k

ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE=nerdfont-complete

export DEFAULT_USER="$USER"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ssh anaconda)
POWERLEVEL9K_ANACONDA_BACKGROUND=green

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

source $ZSH/oh-my-zsh.sh


# local customization
source ~/.rc


if [ -f ~/.zshrc_after ]; then
    source ~/.zshrc_after
fi


# direnv
# https://direnv.net/
# Should be at the end.
eval "$(direnv hook zsh)"
