#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"/..

# Get secret keys from 1Password
eval "$(op signin qobilidop.1password.com qobilidop@gmail.com)"
op get document id_rsa > home/.ssh/id_rsa
chmod 600 home/.ssh/id_rsa
