#!/bin/bash
set -e
cd "$(dirname "$0")"/..

EXTENSIONS="$(code --list-extensions)"

for EXTENSION in $(cat config/vscode-extensions); do
  if echo "$EXTENSIONS" | grep -q "$EXTENSION"; then
    echo "Extension '$EXTENSION' is already installed."
  else
    code --install-extension "$EXTENSION"
  fi
done
