#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"

echo
echo "Setting up Zsh"

# Install
brew install zsh

# Set Zsh as default shell
ZSH="$(command -v zsh)"
if [[ "$SHELL" != "$ZSH" ]]; then
    sudo chsh -s "$ZSH" "$USER"
fi

# Install Oh My Zsh and Powerlevel9k theme
source "$HOME/.zshenv"
OHMYZ="$LOCAL/opt/oh-my-zsh"
./git-sync https://github.com/robbyrussell/oh-my-zsh.git "$OHMYZ"
./git-sync https://github.com/bhilburn/powerlevel9k.git "$OHMYZ/custom/themes/powerlevel9k"
