#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"/..

echo
echo "Setting up crypto keys"

# Install
command -v op || brew cask install 1password-cli

# Extract secret keys from 1Password
eval "$(op signin qobilidop.1password.com qobilidop@gmail.com)"
op get document id_rsa > home/.ssh/id_rsa
chmod 600 home/.ssh/id_rsa
