# Fix fpath
fpath=($default_fpath $fpath)

source ~/.antigen.zsh

# Powerlevel9k theme configurations
export DEFAULT_USER="$USER"
POWERLEVEL9K_COLOR_SCHEME="light"
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ssh anaconda)
POWERLEVEL9K_ANACONDA_BACKGROUND="green"
antigen theme bhilburn/powerlevel9k powerlevel9k

# Local customization
antigen bundle $HOME/.zsh_custom

antigen apply

# Somehow antigen can not be found without soucing again
source ~/.antigen.zsh

# The following line should be at the end
eval "$(direnv hook zsh)"
