- defaults:
    link:
      create: true
      relink: true

- brewfile:
    file: Brewfile

- link:
    ~/.bash-it:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.gitconfig:
    ~/.hyper.js:
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
